Created Shipper APIs with test cases
liveasy97/shipperApi pull request #1
Opened 2021-04-28 10:37 UTC by vivekbhosale

Please check it and let me know if any changes required.

2021-05-04 18:22 UTC, jsrub requested changes
looks mostly ok

2021-05-04 18:22 UTC, jsrub commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Controller/ShipperController.java
> +		}
this logic should be in the service

2021-05-04 18:22 UTC, jsrub commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Dao/ShipperDao.java
> +	Shipper getById(String id);
check if these queries can be avoided by just using hibernate. i.e you can actually have method names like findById(String Id) without @Query annotation and it will serve your purpose.

2021-05-04 18:22 UTC, jsrub commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Controller/ShipperController.java
> +	public ShipperCreateRequest addShipper(@RequestBody Shipper shipper) {
check model names i think it should be ShipperCreateResponse check this everywhere

2021-05-04 18:22 UTC, jsrub commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Model/ShipperCreateRequest.java
> +package com.springboot.ShipperAPI.Model;
check model names

2021-05-04 18:22 UTC, jsrub commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Model/ShipperDeleteRequest.java
> +package com.springboot.ShipperAPI.Model;
check model names

2021-05-04 18:22 UTC, jsrub commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Service/ShipperServiceImpl.java
> +		}
check for valid phone number using regex.

2021-05-04 18:22 UTC, jsrub commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Service/ShipperServiceImpl.java
> +		updateRequest.setMessage(constants.getUpdateSuccess());
can this code be shifted after line 86 instead? i feel it will be cleaner if we do that

2021-05-04 18:27 UTC, jsrub commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Constants/CommonConstants.java
> +@Data
don't use @Data here. instead you should declare all variables as static. then you'll be able to use them like this -> CommonConstants.ERROR. we should also make all variable in uppercase. eg - CommonConstants.NAME_ERROR

2021-05-14 05:50 UTC, vivekbhosale commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Controller/ShipperController.java
> +		}
Done

2021-05-14 05:52 UTC, vivekbhosale commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Dao/ShipperDao.java
> +	Shipper getById(String id);
Done

2021-05-14 06:00 UTC, vivekbhosale commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Controller/ShipperController.java
> +	public ShipperCreateRequest addShipper(@RequestBody Shipper shipper) {
Done

2021-05-14 06:00 UTC, vivekbhosale commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Model/ShipperCreateRequest.java
> +package com.springboot.ShipperAPI.Model;
Done

2021-05-14 06:00 UTC, vivekbhosale commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Model/ShipperDeleteRequest.java
> +package com.springboot.ShipperAPI.Model;
Done

2021-05-14 06:16 UTC, vivekbhosale commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Constants/CommonConstants.java
> +@Data
Done

2021-05-14 06:19 UTC, vivekbhosale commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Service/ShipperServiceImpl.java
> +		}
Done

2021-05-14 06:22 UTC, vivekbhosale commented on ShipperAPI/src/main/java/com/springboot/ShipperAPI/Service/ShipperServiceImpl.java
> +		updateRequest.setMessage(constants.getUpdateSuccess());
Done

2021-05-14 06:43 UTC, closed without merging